def raise_category_already_exist() -> None:
    raise Exception('category with the same name is already in the set')
